server:
  port: 8082

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/
  instance:
    prefer-ip-address: false
    #instanceId: ${spring.application.name}:${server.port}
spring:
  cloud:
    loadbalancer:
      retry:
        enable: true #开启重试机制
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000  #断路器的超时
hello:
  ribbon:
    ConnecTimeout: 250 #请求链接的超时时间
    ReadTimeout: 1000 #请求处理的超时时间
    OkToRetryOnAllOperation: true #对所有操作请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数
