server:
  port: 7001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/931145736/wenshuai.git #配置git仓库位置
          search-paths: spring_cloud_in_action/config_repo  #配置仓库路径下的相对搜索位置，可以配置多个
          username: 931145736  #访问git仓库的用户名
          password: 19940921ws   #访问git仓库的密码
